# [Main Settings]
shell /bin/zsh
term xterm-kitty

confirm_os_window_close 0

# Inside ~/.config/kitty/kitty.conf
repaint_delay 10
input_delay 3
sync_to_monitor yes

# [Font Configuration]
font_family      DejaVuSansM Nerd Font
bold_font        DejaVuSansM Nerd Font Bold
italic_font      DejaVuSansM Nerd Font Italic
bold_italic_font DejaVuSansM Nerd Font Bold Italic
font_size        12.0

# Replicating line-height=25px 
# (12pt is ~16px, so we add 9px or use a multiplier)
modify_font line_height 156%
modify_font baseline 0px

# [Window Settings]
# Replicates pad=7x15 (Vertical Horizontal)
window_padding_width 15 7
remember_window_size  no
initial_window_width  140c
initial_window_height 30c
title Alacritty
# Prevents programs from changing the title
allow_remote_control yes
listen_on unix:/tmp/mykitty

# [Scrollback]
scrollback_lines 10000
wheel_scroll_multiplier 40.0
touch_scroll_multiplier 40.0

# [Cursor & Mouse]
cursor_shape block
cursor_blink_interval 0
mouse_hide_wait 0
focus_follows_mouse no

# [Colors] Catppuccin Mocha
cursor                  #f5e0dc
cursor_text_color       #1e1e2e
foreground              #cdd6f4
background              #000000
selection_foreground    #1e1e2e
selection_background    #f5e0dc

# color0  (surface1)
color0 #45475a
# color1  (red)
color1 #f38ba8
# color2  (green)
color2 #a6e3a1
# color3  (yellow)
color3 #f9e2af
# color4  (blue)
color4 #89b4fa
# color5  (pink)
color5 #f5c2e7
# color6  (teal)
color6 #94e2d5
# color7  (subtext1)
color7 #bac2de

# color8  (surface2)
color8 #585b70
# color9  (red)
color9 #f38ba8
# color10 (green)
color10 #a6e3a1
# color11 (yellow)
color11 #f9e2af
# color12 (blue)
color12 #89b4fa
# color13 (pink)
color13 #f5c2e7
# color14 (teal)
color14 #94e2d5
# color15 (text)
color15 #cdd6f4

# [Key Bindings]
clear_all_shortcuts yes

# Clipboard
map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard
map shift+insert paste_from_selection

# Font Size
map ctrl+equal change_font_size all +2.0
map ctrl+plus  change_font_size all +2.0
map ctrl+minus change_font_size all -2.0
map ctrl+0     change_font_size all 0

# Fullscreen
map f11 toggle_fullscreen

# Scrollback
map alt+shift+k scroll_line_up
map alt+shift+j scroll_line_down
map ctrl+shift+k scroll_page_up
map ctrl+shift+j scroll_page_down
map shift+home scroll_home
map shift+end scroll_end

# [Text Bindings] (Mod1 is Alt)
map alt+r send_text all \x12
map ctrl+delete send_text all \x1b\x44
map alt+h send_text all \x1b[D
map alt+ctrl+shift+h send_text all \xff95
map alt+j send_text all \x1b[B
map alt+shift+l send_text all \x1bf
map alt+shift+h send_text all \x1bb
map alt+k send_text all \x1b[A
map alt+l send_text all \x1b[C
